name: Mirror to latest-feature

on: 
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - 'feature/**'
jobs:
  mirror_job:
    runs-on: ubuntu-latest
    name: Mirror SOURCE_BRANCH_NAME branch to DESTINATION_BRANCH_NAME branch
    steps:
    - name: Get the current branch name
      shell: bash
      run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
      id: getbranch 
    - name: Mirror action step
      id: mirror
      uses: google/mirror-branch-action@v1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        source: ${{ steps.getbranch.outputs.branch }}
        dest: 'latest-feature'
